version: "3"

# docker-compose up --build
services:
  # 컨테이너 빌드
  # docker run --name fastapi -d -p 8000:8800(호스트:컨테이너) fastapiapp
  fastapi:
    build:
      context: .
      dockerfile : Dockerfile
    container_name: fastapi

    ports:
      - "8000:8800"
    
    volumes:
      - /home/ubuntu/Alert-Audio-Text-Decision-Fusion-API:/app 
      #- /home/ubuntu/Alert-Audio-Text-Decision-Fusion-API:/app 
      #- /home/ubuntu/Alert-Audio-Text-Decision-Fusion-API/static:/app/static
      # ec2-user
    command: uvicorn main:app --host 0.0.0.0 --port 8800 --reload
